### ISSUE TITLE
When trying to build the BrewEmbed I get this error

### ISSUE THREAD

**Issue by unlimitedcoder2** [XorTroll/Brew.js#6]
root@81678a6d5bd2:/Brew.js/BrewEmbed\ make
Main.cpp
aarch64-none-elf-g++ -MMD -MP -MF /root/Brew.js/BrewEmbed/build/Main.d -g -w -O2 -ffunction-sections -march=armv8-a -mtune=cortex-a57 -mtp=soft -fPIE  -I/root/Brew.js/BrewEmbed/include -I/opt/devkitpro/portlibs/switch/include -I/opt/devkitpro/libnx/include -I/root/Brew.js/BrewEmbed/build -D__SWITCH__ -fno-rtti -fno-exceptions -std=gnu++11 -c /root/Brew.js/BrewEmbed/source/Main.cpp -o Main.o
In file included from /root/Brew.js/BrewEmbed/source/Brew.js/Brew.js.h:15,
                 from /root/Brew.js/BrewEmbed/source/Main.cpp:2:
/root/Brew.js/BrewEmbed/source/Brew.js/Node/fs.h: In function 'int fs::c_mkdir(duk_context*)':
/root/Brew.js/BrewEmbed/source/Brew.js/Node/fs.h:65:13: error: 'mkdir' was not declared in this scope
             mkdir(dir, 777);
             ^~~~~
/root/Brew.js/BrewEmbed/source/Brew.js/Node/fs.h:65:13: note: suggested alternative: 'dir'
             mkdir(dir, 777);
             ^~~~~
             dir
/opt/devkitpro/devkitA64/base_rules:13: recipe for target 'Main.o' failed
make[1]: *** [Main.o] Error 1
Makefile:151: recipe for target 'build' failed
make: *** [build] Error 2
root@81678a6d5bd2:~/Brew.js/BrewEmbed#

I do not know c/cpp so I am sorry if this is an easy fix and I am being stupid.

**Comment by XorTroll** [comment]
Idk the error for sure, but do you have the latest version of libnx, sdl2 and all the other packages? Try updating then from pacman with "Pac-Man -Syu"

**Comment by XorTroll** [comment]
Hmm, that's quite strange, nobody who built embedding has reported that.
Are you sure everything is updated? Not just sdl2 or libnx, also other libs which are included.
Did you modify anything of the project?

**Comment by unlimitedcoder2** [comment]
I did not modify anything in the project. I am using the devkitpro/devkita64 docker container which was updated last week so I would assume that everything is updated. https://hub.docker.com/r/devkitpro/devkita64/

**Comment by ThatNerdyPikachu** [comment]
I have the same error, all of the required packages are installed with dkp pacman
```
error: 'mkdir' was not declared in this scope
             mkdir(dir, 777);
```

**Comment by XorTroll** [comment]
I modified the embed project here on github, try this one

**Comment by unlimitedcoder2** [comment]
Thanks this has resolved my issue
